# Generated by Django 3.1.6 on 2021-03-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saveDicomFiles',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('dicomFiles', models.FileField(default='', upload_to='dicom/dicomFiles/')),
                ('stlFiles', models.FileField(default='', upload_to='dicom/stlFiles/')),
            ],
        ),
    ]
