# Generated by Django 3.1.6 on 2021-03-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlConverter', '0002_auto_20210325_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecontactdata',
            name='email',
            field=models.EmailField(default='', max_length=35, null=True),
        ),
    ]
