# Generated by Django 3.1.6 on 2021-03-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stlConverter', '0003_auto_20210326_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecontactdata',
            name='feedback',
            field=models.TextField(default='', max_length=400, null=True),
        ),
    ]
